### PR TITLE
Fix Description syntax

### PR DESCRIPTION
**Pull request by jcooter**

### CODE REVIEW

**Review by jacekn — COMMENTED** [review]
Did you use two leading spaces on purpose? Normally single space is better for formatting

**Comment by jcooter** [comment]
I used 2 spaces because that's what the syntax example I referenced did

**Comment by jacekn** [comment]
> I used 2 spaces because that's what the syntax example I referenced did

2 spaces will cause the description to be displayed verbatim. It's normally better to use single space so that the text is part of single paragraph (this is what we do in other control files in this repo)

**Review by jacekn — APPROVED** [review]
LGTM!

**Pull request merged**
